/**
 * @jest-environment jsdom
 */

import * as React from 'react';
import { MultiYearMonthlyRidershipChart } from '@app/utils/MultiYearChart';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom'

describe('MultiYearMonthlyRidershipChart tests', () => {
    test('should render MultiYearMonthlyRidershipChart component', async () => {
        const lineFn = (row: any): number => row.NewportNews;
        const { asFragment } = render(
            <div style={{ height: '300px', width: '600px' }}>
                <MultiYearMonthlyRidershipChart lineFn={lineFn} startYear={1900} />
            </div>
        );
  
    // 1. Target the SVG container elements generated by the Voronoi tracker
    // PatternFly renders hover-targets inside specific SVG paths or rectangles
    const voronoiPaths = asFragment().querySelectorAll('path');
    
    // Safety check ensuring chart elements mounted successfully
    expect(voronoiPaths.length).toBeGreaterThan(0);

    });
});